### ISSUE TITLE
node_elect_test may fail

### ISSUE THREAD

**Issue by xzhangxian1008** [purecpp-org/raftcpp#180]
We can't pass node_elect_test all the time.

**Comment by xzhangxian1008** [comment]
We need to rewrite the node_elect_test to test the related features at least 1000 times.

**Comment by jovany-wang** [comment]
Sounds great. 
How about adding a python integration test? I believe it's hard to write the integration tests in C++. #176

**Comment by xzhangxian1008** [comment]
> Sounds great.
> How about adding a python integration test? I believe it's hard to write the integration tests in C++. #176

I can write a simple batch tests in this test file first. Python integration test will be added later.

**Comment by xzhangxian1008** [comment]
> Sounds great.
> How about adding a python integration test? I believe it's hard to write the integration tests in C++. #176

okk

**Comment by jovany-wang** [comment]
duplicated to #186
