### ISSUE TITLE
node_elect_test will crash

### ISSUE THREAD

**Issue by zhangdexin** [purecpp-org/raftcpp#186]
Env:
```gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)```

I find some bug(or not), need analysis:
1. [166](https://github.com/purecpp-org/raftcpp/blob/master/tests/node_elect_test.cc#L166)
thread destory, but[112](https://github.com/purecpp-org/raftcpp/blob/master/tests/node_elect_test.cc#L112) threads vector also destory thread. double free?
2. node.h[this](https://github.com/purecpp-org/raftcpp/blob/master/src/node/node.h#L77) could ```TimerManager timer_manager_``` to set end, because timer_manager_ need first free.
3. I fix the crash in [pr](https://github.com/purecpp-org/raftcpp/pull/185) can work, but it canot pass test case. 
Becase I need add code in line 163
```
    threads[leaderFlag].join();
    nodes[leaderFlag].reset();
```
But it crash ``` nodes[leaderFlag].reset();``` this line.

**Comment by jovany-wang** [comment]
Is this issue addressed? @zhangdexin

**Comment by jovany-wang** [comment]
Closing it now. Feel free to reopen this once there is update.
