### ISSUE TITLE
TimerManager should hold timer not only for about  elect

### ISSUE THREAD

**Issue by zhangdexin** [purecpp-org/raftcpp#200]
Currently, TimerManager only hold timers for about  elect. TimerManager should hold all timer that is need by the program running.

And so:
- TimerManager object should be init and start at RaftNode, and the object is member of RaftNode.
-  TimerManager object can be  forward to other class by RaftNode
- Other class register timer via TimerManager.

**Comment by jovany-wang** [comment]
How do we make timers dynamically? I mean use a map to store all registered timers, like:

```C++
std::unordered_map<std::string, Timer> all_timers_;
```
