### ISSUE TITLE
there are some errors in config.cc

### ISSUE THREAD

**Issue by hbangq** [purecpp-org/raftcpp#238]
src/common/config.cc:17:56: error: no match for 'operator=' (operand types are 'std::pair<long int, raftcpp::Endpoint>' and 'raftcpp::Endpoint')
   17 |             config.this_endpoint_ = Endpoint(pos->str());

src/common/config.cc:20:49: error: no matching function for call to 'raftcpp::common::Config::PushBack(raftcpp::Endpoint)'
   20 |             config.PushBack(Endpoint(pos->str()));

**Comment by jovany-wang** [comment]
Hi, thanks for the feedback. Could you also give the complier version and what OS you're using?

**Comment by jovany-wang** [comment]
@zavier-wong Could you also take a look?

**Comment by zavier-wong** [comment]
> @zavier-wong Could you also take a look?

OK

**Comment by hbangq** [comment]
> > @zavier-wong Could you also take a look?
> 
> OK

This seems to be because config.h was modified in commit #232, but config.cc was not modified.

**Comment by jovany-wang** [comment]
Hi @hbangq , are you willing to fix it?

**Comment by hbangq** [comment]
> Hi @hbangq , are you willing to fix it?

I am willing to do that, but I need some time to understand the code.

**Comment by jovany-wang** [comment]
@hbangq Great. It's okay.
